# Base config shared by all datasets

defaults: # these are the sub-config files for specific details, noee for the moment.
  - _self_ # this makes the top-level config take priority over sub-configs, see https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order/
  - model: model
  - data: data

mode:
  eval_only: false    # overridden by CLI


evaluation:
  results_output_dir: "eval_results"
  cv_folds: 5
  grid_search_cv_folds: 5
  grid_search_scoring: "roc_auc"
  grid_search_random_state: 20260101
  final_eval_random_state: 20260101
  save_normalized_cm: true

valid_dataset_names: [Tanaka, Diabimmune, Goldberg, Gadir]

tracking:
  enabled: false
  publish_to_main: false
  project: "gut-microbiome-experiments"
  run_name: null
  tags: ["gridsearch", "unbiased-cv"]
  space_id: "vaibhav2507/gut-microbiome"
